name: ✅ Task
description: 작업의 목적과 세부 사항을 기록하는 템플릿입니다.
title: "[TASK] 작업 제목을 입력하세요"
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📝 Summary
        작업의 목적과 목표를 간단히 설명하세요.

  - type: textarea
    id: summary
    attributes:
      label: 작업 요약
      description: 작업의 목적과 목표를 작성하세요.
      placeholder: 작업의 목표를 간단히 입력하세요.
      value: ""

  - type: markdown
    attributes:
      value: |
        ### 📋 Details
        작업의 구체적인 내용을 작성하세요.

  - type: textarea
    id: details
    attributes:
      label: 작업 세부 사항
      description: 작업을 수행하기 위한 구체적인 단계를 작성하세요.
      placeholder: - [세부 작업 1]  
                   - [세부 작업 2]
      value: ""

  - type: markdown
    attributes:
      value: |
        ### 🔗 Additional Information
        참고할 링크나 추가 설명이 있다면 작성하세요.

  - type: input
    id: additional-info
    attributes:
      label: 추가 정보
      description: 참고 자료나 관련 링크를 입력하세요.
      placeholder: 추가 정보를 입력하세요.
      value: ""
